

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(MASS)
library(purrr)
library(tidyr)
```

```{r read-in}
gym_data = read.csv("data_2022_2023.csv")
head(gym_data)
```

```{r}
#Cleaning hb issue
gym_data$Apparatus[gym_data$Apparatus == "hb"] <- "HB"
```

```{r Highest-Vault}
#Gymnasts vault two times, which is in the data as VT1 and VT2 (or if just once VT)
#Renaming these to all just be VT, because they're all data on vaults
gym_data$Apparatus[gym_data$Apparatus == "VT1"] <- "VT"
gym_data$Apparatus[gym_data$Apparatus == "VT2"] <- "VT"

#Making a US Binary variable
gym_data <- gym_data %>%
  mutate(Nation = case_when(Country == "USA" ~ "USA",
                              Country != "USA" ~ "Other"))
```

```{r}
men_gym_data %>%
  group_by(Apparatus)%>%
  summarize(max(Score))

women_gym_data %>%
  group_by(Apparatus)%>%
  summarize(max(Score))
```

```{r}
men_gym_data %>%
  group_by(LastName, Competition)%>%
  filter(Apparatus == "PB")%>%
  summarize(max(Score))
```
```{r}
gym_data %>%
  group_by(Competition, Round)%>%
  summarize(max(Score))
```
```{r}
women_gym_data %>%
  filter(Apparatus == "UB")%>%
  group_by(LastName, Rank, Competition)%>%
  summarize(min(Rank))%>%
  arrange(Rank)

women_gym_data %>%
  group_by(LastName)%>%
  filter(Rank == 1) %>%
  count(Rank == 1)%>%
  arrange(desc(n))
  
men_gym_data %>%
  group_by(LastName)%>%
  filter(Rank == 1) %>%
  count(Rank == 1)%>%
  arrange(desc(n))
```

```{r}
ggplot(data = gym_data, aes(x = Apparatus, y = E_Score))+
  geom_violin()
```

```{r}
men_gym_data %>%
  group_by(Apparatus, FirstName, LastName)%>%
  mutate(avg_score = mean(Score))%>%
  select(FirstName, LastName, avg_score)

avg_rank_men <- men_gym_data %>%
  group_by(FirstName, LastName)%>%
  mutate(avg_rank = mean(Rank))%>%
  select(FirstName, LastName, avg_rank)%>%
  distinct(FirstName, LastName, avg_rank)%>%
  arrange(avg_rank)

avg_rank_men_na <- na.omit(avg_rank_men)
avg_rank_men_na
```

```{r}
hist(men_gym_data$Score)
hist(women_gym_data$Score)
hist(men_gym_data$Rank)
hist(women_gym_data$Rank)

```

```{r}
alpha <- 9
beta <- 2
x <- seq(0,1, length = 24434)
y <-dbeta(gym_data$Score, shape1 = alpha, shape2 = beta)

plot(x, y, type = "l", col = "blue", lwd = 2, xlab = "x", ylab = "Density",
     main = "Beta Distribution")

# Add labels and legend
legend("topright", legend = paste("Beta(", alpha, ",", beta, ")", sep = ""), col = "blue", lwd = 2)


curve(dbeta(x, shape1 = alpha, shape2 = beta), from = 0, to = 1, n = 22842,
      col = "blue", lwd = 2, xlab = "x", ylab = "Density",
      main = "Beta Distribution", type = "l")
```
```{r}
hist(uniques$Score)
x <- seq(0,1, length = 24434)
y <- dgamma(uniques$Score, shape = 2, rate = 1)
fit_gam <- fitdistr(uniques$Score, "gamma", start = list(shape = 2, rate = 1))
```


```{r}
problematic_groups <- cleaned_gym_data %>%
  filter(FirstName == "" | LastName == "" | FirstName == ".")%>%
  distinct()

# Filter out problematic groups from the original data
uniques <- cleaned_gym_data %>%
  anti_join(problematic_groups, by = c("FirstName", "LastName"))

uniques <- uniques %>%
  distinct(FirstName, LastName, Score, Country, Gender)

fit_norm <- fitdistr(uniques$Score, "normal")
print(fit_norm$estimate)
print(fit_gam$estimate)

mu <- fit_norm$estimate[1]
sd <- fit_norm$estimate[2]

likelihood_vector <- dnorm(uniques$Score, mean = mu, sd = sd)
uniques$Likelihood <- likelihood_vector
print(uniques[, c("Score", "Likelihood")])

quantile_95 <- qnorm(0.95, mean = mu, sd = sd)

usa <- subset(uniques, Country == "USA")

topUSA <- usa%>%
  filter(usa$Score >= quantile_95)

topUSA %>%
  group_by(FirstName, LastName, Gender)%>%
  mutate(mean_score = mean(Score))%>%
  arrange(desc(mean_score))%>%
  distinct(FirstName, LastName, mean_score)
```


```{r}
problematic_groups <- cleaned_gym_data %>%
  filter(FirstName == "" | LastName == "" | FirstName == ".")%>%
  distinct()

# Filter out problematic groups from the original data
uniques <- cleaned_gym_data %>%
  anti_join(problematic_groups, by = c("FirstName", "LastName"))%>%
  filter(!is.na(Score))
usa <- subset(uniques, Country == "USA")
usa_men <- subset(usa, Gender == "m")
usa_women <- subset(usa, Gender == "w")

mu <- list()
sd <- list()
name_store <- list()
for(i in 1:nrow(usa_men)){
  first_name <- usa_men$FirstName[i]
  last_name <- usa_men$LastName[i]
  name_store[[i]] <- paste(first_name, last_name, i , sep = "-")
  sub <- usa_men %>%
    subset(LastName == last_name)%>%
    subset(FirstName == first_name)
  sub_na <- na.omit(sub$Score)
  fits <- fitdistr(sub$Score, "normal")
  mu[[i]] <- as.numeric(fits$estimate[1])
  sd[[i]] <- as.numeric(fits$estimate[2])
}

men_tib <- tibble(Names = name_store, Mu = mu, SD = sd)
men_tib$Names <- sub("^(.*?-.*?)-.*", "\\1", men_tib$Names)

men_usa <- men_tib %>%
  distinct(Names, Mu, SD)

mu_2 <- list()
sd_2 <- list()
name_store_2 <- list()
for(i in 1:nrow(usa_women)){
  first_name <- usa_women$FirstName[i]
  last_name <- usa_women$LastName[i]
  name_store_2[[i]] <- paste(first_name, last_name, i , sep = "-")
  sub <- usa_women %>%
    subset(LastName == last_name)%>%
    subset(FirstName == first_name)
  sub_na <- na.omit(sub$Score)
  fits <- fitdistr(sub$Score, "normal")
  mu_2[[i]] <- as.numeric(fits$estimate[1])
  sd_2[[i]] <- as.numeric(fits$estimate[2])
}

women_tib <- tibble(Names = name_store_2, Mu = mu_2, SD = sd_2)
women_tib$Names <- sub("^(.*?-.*?)-.*", "\\1", women_tib$Names)

women_usa <- women_tib %>%
  distinct(Names, Mu, SD)
```

```{r check-no-lost-info}
filtered_data <- cleaned_gym_data %>%
  filter(Country == "USA")%>%
  distinct(FirstName, LastName)%>%
  count(FirstName)%>%
  mutate(total = sum(n))

```

```{r}
n <- 10000
gymnasts <- 6
top_combos <- 10
usa_unique_final <- na.omit(men_usa)
  
#simulate_composite_score <- function(selected_gymnasts) {
#  simulated_scores <- lapply(selected_gymnasts$Mu, function(mu) rnorm(length(mu), mean = mu, sd = #sd))
#  composite_score <- rowSums(do.call(cbind, simulated_scores))
#  return(sum(composite_score))
#}

simulate_composite_score <- function(selected_gymnasts) {
  simulated_scores <- list()
  composite_score <- 0
  for (i in 1: nrow(selected_gymnasts)) {
    if(!is.na(selected_gymnasts$SD[i])){
      dev <- as.numeric(selected_gymnasts$SD[i])
    } else{
      dev = 0
    }
    mu <- as.numeric(selected_gymnasts$Mu[i])
    if (!is.na(dev) && abs(dev) < 1e-10) {
      simulated_scores[[i]] <- mu
    } else {
      simulated_scores[[i]] <- rnorm(1, mean = mu, sd = dev)
    }
    composite_score <- composite_score + as.numeric(simulated_scores[[i]])
#    cat("Iteration:", i, "mu:", mu, "dev:", dev, "Simulated Score:", simulated_scores[[i]], "Composite Score:", composite_score, "\n")
  }  
#  print(composite_score)
  return(composite_score)
}

results <- replicate(n, {
  sampled_gymnasts <- usa_unique_final[sample(nrow(usa_unique_final), gymnasts, replace = FALSE),]
  composite_score <- simulate_composite_score(sampled_gymnasts)
  results_entry <- c(Gymnasts = paste(sampled_gymnasts$Names, collapse = ", "), Composite_Score = composite_score)
  results_entry
})
results_tibble <- as_tibble(t(results))

top_combinations_df <- results_tibble %>%
  arrange(desc(Composite_Score)) %>%
  slice_head(n = 10)

print(top_combinations_df)
```

```{r}
n <- 10000
gymnasts <- 6
top_combos <- 10
usa_unique_final <- na.omit(women_usa)
  
#simulate_composite_score <- function(selected_gymnasts) {
#  simulated_scores <- lapply(selected_gymnasts$Mu, function(mu) rnorm(length(mu), mean = mu, sd = #sd))
#  composite_score <- rowSums(do.call(cbind, simulated_scores))
#  return(sum(composite_score))
#}

simulate_composite_score <- function(selected_gymnasts) {
  simulated_scores <- list()
  composite_score <- 0
  for (i in 1: nrow(selected_gymnasts)) {
    if(!is.na(selected_gymnasts$SD[i])){
      dev <- as.numeric(selected_gymnasts$SD[i])
    } else{
      dev = 0
    }
    mu <- as.numeric(selected_gymnasts$Mu[i])
    if (!is.na(dev) && abs(dev) < 1e-10) {
      simulated_scores[[i]] <- mu
    } else {
      simulated_scores[[i]] <- rnorm(1, mean = mu, sd = dev)
    }
    composite_score <- composite_score + as.numeric(simulated_scores[[i]])
#    cat("Iteration:", i, "mu:", mu, "dev:", dev, "Simulated Score:", simulated_scores[[i]], "Composite Score:", composite_score, "\n")
  }  
#  print(composite_score)
  return(composite_score)
}

results <- replicate(n, {
  sampled_gymnasts <- usa_unique_final[sample(nrow(usa_unique_final), gymnasts, replace = FALSE),]
  composite_score <- simulate_composite_score(sampled_gymnasts)
  results_entry <- c(Gymnasts = paste(sampled_gymnasts$Names, collapse = ", "), Composite_Score = composite_score)
  results_entry
})
results_tibble <- as_tibble(t(results))

top_combinations_df <- results_tibble %>%
  arrange(desc(Composite_Score)) %>%
  slice_head(n = 10)

print(top_combinations_df)
```